/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as ButtonIndexImport } from './routes/button/index'
import { Route as BadgeIndexImport } from './routes/badge/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ButtonIndexRoute = ButtonIndexImport.update({
  id: '/button/',
  path: '/button/',
  getParentRoute: () => rootRoute,
} as any)

const BadgeIndexRoute = BadgeIndexImport.update({
  id: '/badge/',
  path: '/badge/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/badge/': {
      id: '/badge/'
      path: '/badge'
      fullPath: '/badge'
      preLoaderRoute: typeof BadgeIndexImport
      parentRoute: typeof rootRoute
    }
    '/button/': {
      id: '/button/'
      path: '/button'
      fullPath: '/button'
      preLoaderRoute: typeof ButtonIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/badge': typeof BadgeIndexRoute
  '/button': typeof ButtonIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/badge': typeof BadgeIndexRoute
  '/button': typeof ButtonIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/badge/': typeof BadgeIndexRoute
  '/button/': typeof ButtonIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/badge' | '/button'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/badge' | '/button'
  id: '__root__' | '/' | '/badge/' | '/button/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BadgeIndexRoute: typeof BadgeIndexRoute
  ButtonIndexRoute: typeof ButtonIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BadgeIndexRoute: BadgeIndexRoute,
  ButtonIndexRoute: ButtonIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/badge/",
        "/button/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/badge/": {
      "filePath": "badge/index.tsx"
    },
    "/button/": {
      "filePath": "button/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
